ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = Adafruit_HTU21DF DHT RS485_protocol SoftwareSerial Wire Wire/utility SPI Ethernet
include /usr/share/arduino/Arduino.mk

